### ISSUE TITLE
Adding in In-App Notifications or tying them to web-push?

### ISSUE THREAD

**Issue by alex-roger-1942** [notifme/notifme-sdk#53]
I'm looking at this exciting tool your team has been working on and hoping to adopt it, however I have a question after reading through the documentation.

Is there any way to tie this into my web-app? I saw web-push but wasn't entirely sure how this works?

Essentially I would like to have something similar to facebook or google plus as an option where I Have a bell that a user can click to view their notification history after the webpush has happened and be able to query their own personal notification history on a specific channel.

Is this something that exists? How would this work?

I didn't see any GET or websocket option in the documentation. If this is something that could be voted for I would cast my vote :)

I could see this as somekind of websocket provider

channel: My-App-Push-Channel -> (Store value for Later GET) -> Websocket Gateway -> App Subscribed to websocket gateway.

**Comment by BDav24** [comment]
> I saw web-push but wasn't entirely sure how this works?

Web pushes are notifications handled by browsers (desktop and mobile: https://caniuse.com/#feat=push-api). You can check this tool out: https://www.notif.me/preview/webpush

> user can click to view their notification history

This is not a use case for this lib, because it's not stateful (not connected to any database).

> Is this something that exists?

As a saas I guess, as an open source lib I don't know.

> How would this work?

It shouldn't be very complex to store the notification and serve it through an api or websocket.
I developped a tool to display notification history to admins: https://github.com/notifme/notifme-history
I does a part of the job, but a solution to handle user authentification would be necessary to be used like you say.
